adv_temp: 1.0
calc_hits:
- 1
- 3
- 10
check_per_epoch: 5
data_class: KGDataModule
data_path: dataset/FB15K237
dataset_name: FB15K237
early_stop_patience: 3
emb_dim: 1000
eval_bs: 16
eval_task: link_prediction
filter_flag: true
gpu: cuda:0
litmodel_name: KGELitModel
loss_name: Adv_Loss
lr: 0.0001
margin: 9.0
max_epochs: 30
model_name: TransE
negative_adversarial_sampling: true
num_neg: 256
optim_name: Adam
seed: 666
shuffle: true
test_sampler_class: TestSampler
train_bs: 1024
train_sampler_class: UniSampler
use_wandb: false
use_weight: true
