accelerator: null
accumulate_grad_batches: null
adv_temp: 1.0
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
axiom_types: 10
axiom_weight: 1.0
benchmark: false
bn: true
calc_hits:
- 1
- 3
- 10
check_per_epoch: 10
check_val_every_n_epoch: 1
checkpoint_callback: null
checkpoint_dir: ''
comp_op: mul
config_path: ''
data_class: KGDataModule
data_path: dataset/WN18RR
dataset_name: WN18RR
decoder_model: null
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
dis_order: 2
dropout: 0.5
early_stop_patience: 5
emb_dim: 200
emb_shape: 20
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
ent_drop: 0.2
ent_drop_pred: 0.3
epoch_GAT: 3000
eval_bs: 256
eval_task: link_prediction
fast_dev_run: false
fc_drop: 0.1
fet_drop: 0.2
filter_flag: true
flush_logs_every_n_steps: null
freq_init: 4
gpu: cuda:0
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hid_drop: 0.4
hid_size: 49000
hid_size_component: 3648
inject_triple_percent: 1.0
inp_drop: 0.0
ipus: null
k_h: 10
k_w: 20
ker_sz: 7
kg_layer: 1
label_smooth: 0.1
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
litmodel_name: SEGNNLitModel
load_config: false
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss_name: Cross_Entropy_Loss
lr: 0.0015
margin: 12.0
max_entialments: 2000
max_epochs: 800
max_steps: -1
max_time: null
maxsteps: 647200
min_epochs: null
min_steps: null
model_name: SEGNN
modulus_weight: 1.0
move_metrics_to_cpu: false
mu: 10
multiple_trainloader_mode: max_size_cycle
neg_weight: 50
negative_adversarial_sampling: true
norm_flag: false
num_batches: 0
num_ent: 40943
num_layers: 2
num_neg: 10
num_nodes: 1
num_processes: 1
num_rel: 22
num_sanity_val_steps: 2
num_workers: 10
opn: corr
optim_name: Adam
out_channel: 250
out_dim: 200
overfit_batches: 0.0
partial_2hop: false
phase_weight: 1.0
plugins: null
precision: 32
pred_rel_w: true
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
regularization: 0.0
regularization_two: 0
rel_drop: 0.0
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
rm_rate: 0.5
save_config: false
seed: 321
select_probability: 0.8
shuffle: true
slackness_penalty: 0.01
smoothing: 0.1
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
test_only: false
test_sampler_class: SEGNNTestSampler
tpu_cores: null
track_grad_norm: -1
train_bs: 256
train_sampler_class: SEGNNTrainSampler
update_axiom_per: 2
use_wandb: true
use_weight: false
val_check_interval: 1.0
warm_up_steps: 4045
warmup_epoch: 5
weight_decay: 0.01
weights_save_path: null
weights_summary: top
